# Generated by Django 3.2.4 on 2021-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=100, verbose_name='Objetivo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('assigned', 'ASIGNADO'), ('failed', 'FALLADO'), ('completed', 'COMPLETADO')], default='assigned', max_length=10, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
