# Generated by Django 3.2.4 on 2021-06-25 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='hitman',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True), ('role__in', ['hitman', 'manager'])), on_delete=django.db.models.deletion.CASCADE, related_name='hitman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hit',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
